export const GET_DOGS_FOR_CHART_PENDING = "GET_DOGS_FOR_CHART_PENDING";
export const GET_DOGS_FOR_CHART_SUCCESS = "GET_DOGS_FOR_CHART_SUCCESS";
export const GET_DOGS_FOR_CHART_REJECT = "GET_DOGS_FOR_CHART_REJECT";

export const GET_ALL_USERS_BY_CHART_ROLE_PENDING =
  "GET_ALL_USERS_BY_CHART_ROLE_PENDING";
export const GET_ALL_USERS_BY_CHART_ROLE_SUCCESS =
  "GET_ALL_USERS_BY_CHART_ROLE_SUCCESS";
export const GET_ALL_USERS_BY_CHART_ROLE_REJECTED =
  "GET_ALL_USERS_BY_CHART_ROLE_REJECTED";

export const GET_ALL_WALKS_BY_CHART_PENDING = "GET_ALL_WALKS_BY_CHART_PENDING";
export const GET_ALL_WALKS_BY_CHART_SUCCESS = "GET_ALL_WALKS_BY_CHART_SUCCESS";
export const GET_ALL_WALKS_BY_CHART_REJECT = "GET_ALL_WALKS_BY_CHART_REJECT";
