export const CREATE_MESSAGE_PENDING = "CREATE_MESSAGE_PENDING";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_REJECT = "CREATE_MESSAGE_REJECT";

export const GET_MESSAGES_PENDING = "GET_MESSAGES_PENDING";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_REJECT = "GET_MESSAGES_REJECT";

export const CLEAR_CHAT_SUCCESS = "CLEAR_CHAT_SUCCESS";
