export const CREATE_DOG_PENDING = "CREATE_DOG_PENDING";
export const CREATE_DOG_SUCCESS = "CREATE_DOG_SUCCESS";
export const CREATE_DOG_REJECT = "CREATE_DOG_REJECT";

export const GET_DOGS_PENDING = "GET_DOGS_PENDING";
export const GET_DOGS_SUCCESS = "GET_DOGS_SUCCESS";
export const GET_DOGS_REJECT = "GET_DOGS_REJECT";

export const GET_DOGS_BY_USER_PENDING = "GET_DOGS_BY_USER_PENDING";
export const GET_DOGS_BY_USER_SUCCESS = "GET_DOGS_BY_USER_SUCCESS";
export const GET_DOGS_BY_USER_REJECT = "GET_DOGS_BY_USER_REJECT";

export const GET_DOG_BY_ID_PENDING = "GET_DOG_BY_ID_PENDING";
export const GET_DOG_BY_ID_SUCCESS = "GET_DOG_BY_ID_SUCCESS";
export const GET_DOG_BY_ID_REJECT = "GET_DOG_BY_ID_REJECT";

export const DELETE_DOG_BY_ID_PENDING = "DELETE_DOG_BY_ID_PENDING";
export const DELETE_DOG_BY_ID_REJECT = "DELETE_DOG_BY_ID_REJECT";
export const DELETE_DOG_BY_ID_SUCCESS = "DELETE_DOG_BY_ID_SUCCESS";

export const EDIT_DOG_PENDING = "EDIT_DOG_PENDING";
export const EDIT_DOG_REJECT = "EDIT_DOG_REJECT";
export const EDIT_DOG_SUCCESS = "EDIT_DOG_SUCCESS";

export const GET_BREEDS_PENDING = "GET_BREEDS_PENDING";
export const GET_BREEDS_SUCCESS = "GET_BREEDS_SUCCESS";
export const GET_BREEDS_REJECT = "GET_BREEDS_REJECT";

export const FILTER_DOGS_PENDING = "FILTER_DOGS_PENDING";
export const FILTER_DOGS_SUCCESS = "FILTER_DOGS_SUCCESS";
export const FILTER_DOGS_REJECT = "FILTER_DOGS_REJECT";
