export const GET_HELPS_PENDING = "GET_HELPS_PENDING";
export const GET_HELPS_SUCCESS = "GET_HELPS_SUCCESS";
export const GET_HELPS_REJECT = "GET_HELPS_REJECT";

export const DETAIL_HELP_PENDING = "DEATIL_HELP_PENDING";
export const DETAIL_HELP_SUCCESS = "DETAIL_HELP_SUCCESS";
export const DETAIL_HELP_REJECT = "DETAIL_HELP_REJECT";

export const CREATE_HELP_PENDING = "CREATE_HELP_PENDING";
export const CREATE_HELP_SUCCESS = "CREATE_HELP_SUCCESS";
export const CREATE_HELP_REJECT = "CREATE_HELP_REJECT";

export const DELETE_HELP_PENDING = "DELETE_HELP_PENDING";
export const DELETE_HELP_SUCCESS = "DELETE_HELP_SUCCESS";
export const DELETE_HELP_REJECT = "DELETE_HELP_REJECT";
