export const CREATE_NOTIFICATION_PENDING = "CREATE_NOTIFICATION_PENDING";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_REJECT = "CREATE_NOTIFICATION_REJECT";

export const GET_NOTIFICATIONS_PENDING = "GET_NOTIFICATIONS_PENDING";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_REJECT = "GET_NOTIFICATIONS_REJECT";

export const CHANGE_STATUS_NOTIFICATION_PENDING = "CHANGE_STATUS_NOTIFICATION_PENDING";
export const CHANGE_STATUS_NOTIFICATION_SUCCESS = "CHANGE_STATUS_NOTIFICATION_SUCCESS";
export const CHANGE_STATUS_NOTIFICATION_REJECT = "CHANGE_STATUS_NOTIFICATION_REJECT";

export const DELETE_NOTIFICATION_PENDING = "DELETE_NOTIFICATION_PENDING";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_REJECT = "DELETE_NOTIFICATION_REJECT";