export const GET_ORDERS_BY_USER_PENDING = "GET_ORDERS_BY_USER_PENDING";
export const GET_ORDERS_BY_USER_REJECT = "GET_ORDERS_BY_USER_REJECT";
export const GET_ORDERS_BY_USER_SUCCESS = "GET_ORDERS_BY_USER_SUCCESS";

export const GET_ALL_ORDERS_PENDING = "GET_ALL_ORDERS_PENDING";
export const GET_ALL_ORDERS_REJECT = "GET_ALL_ORDERS_REJECT";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";

export const FILTER_ORDERS_PENDING = "FILTER_ORDERS_PENDING";
export const FILTER_ORDERS_SUCCESS = "FILTER_ORDERS_SUCCESS";
export const FILTER_ORDERS_REJECT = "FILTER_ORDERS_REJECT";