export const GET_POST_PENDING = "GET_POST_PENDING";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_REJECT = "GET_POST_REJECT";

export const DETAIL_POST_PENDING = "DETAIL_POST_PENDING";
export const DETAIL_POST_SUCCESS = "DETAIL_POST_SUCCESS";
export const DETAIL_POST_REJECT = "DETAIL_POST_REJECT";

export const CREATE_POST_PENDING = "CREATE_POST_PENDING";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_REJECT = "CREATE_POST_REJECT";

export const DELETE_POST_PENDING = "DELETE_POST_PENDING";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_REJECT = "DELETE_POST_REJECT";

export const EDIT_POST_PENDING = "EDIT_POST_PENDING";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_REJECT = "EDIT_POST_REJECT";

export const GET_POSTCOMMENTS_PENDING = "GET_POSTCOMMENTS_PENDING";
export const GET_POSTCOMMENTS_SUCCESS = "GET_POSTCOMMENTS_SUCCESS";
export const GET_POSTCOMMENTS_REJECT = "GET_POSTCOMMENTS_REJECCREATE";

export const CREATE_POSTCOMMENTS_PENDING = "CREATE_POSTCOMMENTS_PENDING";
export const CREATE_POSTCOMMENTS_SUCCESS = "CREATE_POSTCOMMENTS_SUCCESS";
export const CREATE_POSTCOMMENTS_REJECT = "CREATE_POSTCOMMENTS_REJECT";

export const EDIT_POSTCOMMENTS_PENDING = "EDIT_POSTCOMMENTS_PENDING";
export const EDIT_POSTCOMMENTS_SUCCESS = "EDIT_POSTCOMMENTS_SUCCESS";
export const EDIT_POSTCOMMENTS_REJECT = "EDIT_POSTCOMMENTS_REJECT";

export const DELETE_POSTCOMMENTS_PENDING = "DELETE_POSTCOMMENTS_PENDING";
export const DELETE_POSTCOMMENTS_SUCCESS = "DELETE_POSTCOMMENTS_SUCCESS";
export const DELETE_POSTCOMMENTS_REJECT = "DELETE_POSTCOMMENTS_REJECT";

export const SEARCH_BY_TITLE_POSTS_PENDING = "SEARCH_BY_TITLE_POSTS_PENDING";
export const SEARCH_BY_TITLE_POSTS_SUCCESS = "SEARCH_BY_TITLE_POSTS_SUCCESS";
export const SEARCH_BY_TITLE_POSTS_REJECT = "SEARCH_BY_TITLE_POSTS_REJECT";

export const FILTER_BY_CATEGORY_POSTS_PENDING =
  "FILTER_BY_CATEGORY_POSTS_PENDING";
export const FILTER_BY_CATEGORY_POSTS_SUCCESS =
  "FILTER_BY_CATEGORY_POSTS_SUCCESS";
export const FILTER_BY_CATEGORY_POSTS_REJECT =
  "FILTER_BY_CATEGORY_POSTS_REJECT";
