export const CREATE_RESERVE_PENDING = "CREATE_RESERVE_PENDING";
export const CREATE_RESERVE_REJECT = "CREATE_RESERVE_REJECT";
export const CREATE_RESERVE_SUCCESS = "CREATE_RESERVE_SUCCESS";

export const GET_ALL_RESERVES_PENDING = "GET_ALL_RESERVES_PENDING";
export const GET_ALL_RESERVES_REJECTED = "GET_ALL_RESERVES_REJECTED";
export const GET_ALL_RESERVES_SUCCESS = "GET_ALL_RESERVES_SUCCESS";

export const GET_RESERVE_BY_ID_PENDING = "GET_RESERVE_BY_ID_PENDING";
export const GET_RESERVE_BY_ID_REJECT = "GET_RESERVE_BY_ID_REJECT";
export const GET_RESERVE_BY_ID_SUCCESS = "GET_RESERVE_BY_ID_SUCCESS";

export const DELETE_RESERVE_BY_ID_PENDING = "DELETE_RESERVE_BY_ID_PENDING";
export const DELETE_RESERVE_BY_ID_REJECT = "DELETE_RESERVE_BY_ID_REJECT";
export const DELETE_RESERVE_BY_ID_SUCCESS = "DELETE_RESERVE_BY_ID_SUCCESS";

export const GET_ALL_RESERVES_OWNER_PENDING = "GET_ALL_RESERVES_OWNER_PENDING";
export const GET_ALL_RESERVES_OWNER_REJECTED =
  "GET_ALL_RESERVES_OWNER_REJECTED";
export const GET_ALL_RESERVES_OWNER_SUCCESS = "GET_ALL_RESERVES_OWNER_SUCCESS";

export const GET_ALL_RESERVES_WALKER_PENDING =
  "GET_ALL_RESERVES_WALKER_PENDING";
export const GET_ALL_RESERVES_WALKER_REJECTED =
  "GET_ALL_RESERVES_WALKER_REJECTED";
export const GET_ALL_RESERVES_WALKER_SUCCESS =
  "GET_ALL_RESERVES_WALKER_SUCCESS";

export const DELETE_RESERVE_BY_WALKID_PENDING =
  "DELETE_RESERVE_BY_WALKID_PENDING";
export const DELETE_RESERVE_BY_WALKID_REJECT =
  "DELETE_RESERVE_BY_WALKID_REJECT";
export const DELETE_RESERVE_BY_WALKID_SUCCESS =
  "DELETE_RESERVE_BY_WALKID_SUCCESS";

export const UPDATE_RESERVE_PENDING = "UPDATE_RESERVE_PENDING";
export const UPDATE_RESERVE_REJECT = "UPDATE_RESERVE_REJECT";
export const UPDATE_RESERVE_SUCCESS = "UPDATE_RESERVE_SUCCESS";

export const GET_ALL_RESERVES_FILTERS_PENDING =
  "GET_ALL_RESERVES_FILTERS_PENDING";
export const GET_ALL_RESERVES_FILTERS_REJECTED =
  "GET_ALL_RESERVES_FILTERS_REJECTED";
export const GET_ALL_RESERVES_FILTERS_SUCCESS =
  "GET_ALL_RESERVES_FILTERS_SUCCESS";

export const GET_DOGS_RESERVES_PENDING = "GET_DOGS_RESERVES_PENDING";
export const GET_DOGS_RESERVES_REJECTED = "GET_DOGS_RESERVES_REJECTED";
export const GET_DOGS_RESERVES_SUCCESS = "GET_DOGS_RESERVES_SUCCESS";

export const GET_ACCEPTED_RESERVES_WALKER_PENDING =
  "GET_ACCEPTED_RESERVES_WALKER_PENDING";
export const GET_ACCEPTED_RESERVES_WALKER_REJECTED =
  "GET_ACCEPTED_RESERVES_WALKER_REJECTED";
export const GET_ACCEPTED_RESERVES_WALKER_SUCCESS =
  "GET_ACCEPTED_RESERVES_WALKER_SUCCESS";

export const GET_PENDING_RESERVES_WALKER_PENDING =
  "GET_PENDING_RESERVES_WALKER_PENDING";
export const GET_PENDING_RESERVES_WALKER_REJECTED =
  "GET_PENDING_RESERVES_WALKER_REJECTED";
export const GET_PENDING_RESERVES_WALKER_SUCCESS =
  "GET_PENDING_RESERVES_WALKER_SUCCESS";

export const GET_COMPLETED_RESERVES_WALKER_PENDING =
  "GET_COMPLETED_RESERVES_WALKER_PENDING";
export const GET_COMPLETED_RESERVES_WALKER_REJECTED =
  "GET_COMPLETED_RESERVES_WALKER_REJECTED";
export const GET_COMPLETED_RESERVES_WALKER_SUCCESS =
  "GET_COMPLETED_RESERVES_WALKER_SUCCESS";

export const GET_PENDING_RESERVES_OWNER_PENDING =
  "GET_PENDING_RESERVES_OWNER_PENDING";
export const GET_PENDING_RESERVES_OWNER_REJECTED =
  "GET_PENDING_RESERVES_OWNER_REJECTED";
export const GET_PENDING_RESERVES_OWNER_SUCCESS =
  "GET_PENDING_RESERVES_OWNER_SUCCESS";

export const GET_COMPLETED_RESERVES_OWNER_PENDING =
  "GET_COMPLETED_RESERVES_OWNER_PENDING";
export const GET_COMPLETED_RESERVES_OWNER_REJECTED =
  "GET_COMPLETED_RESERVES_OWNER_REJECTED";
export const GET_COMPLETED_RESERVES_OWNER_SUCCESS =
  "GET_COMPLETED_RESERVES_OWNER_SUCCESS";

export const GET_ACCEPTED_RESERVES_OWNER_PENDING =
  "GET_ACCEPTED_RESERVES_OWNER_PENDING";
export const GET_ACCEPTED_RESERVES_OWNER_REJECTED =
  "GET_ACCEPTED_RESERVES_OWNER_REJECTED";
export const GET_ACCEPTED_RESERVES_OWNER_SUCCESS =
  "GET_ACCEPTED_RESERVES_OWNER_SUCCESS";

export const UPDATE_RESERVES_PENDING = "UPDATE_RESERVES_PENDING";
export const UPDATE_RESERVES_SUCCESS = "UPDATE_RESERVES_SUCCESS";
export const UPDATE_RESERVES_REJECT = "UPDATE_RESERVES_REJECT";

export const PAY_RESERVES_PENDING = "PAY_RESERVES_PENDING";
export const PAY_RESERVES_REJECT = "PAY_RESERVES_REJECT";
export const PAY_RESERVES_SUCCESS = "PAY_RESERVES_SUCCESS";

export const PAY_STATUS_PENDING = "PAY_STATUS_PENDING";
export const PAY_STATUS_REJECT = "PAY_STATUS_REJECT";
export const PAY_STATUS_SUCCESS = "PAY_STATUS_SUCCESS";

export const GET_USER_ORDERS_PENDING = "GET_USER_ORDERS_PENDING";
export const GET_USER_ORDERS_REJECT = "GET_USER_ORDERS_REJECT";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";

export const GET_ALL_ORDERS_PENDING = "GET_ALL_ORDERS_PENDING";
export const GET_ALL_ORDERS_REJECT = "GET_ALL_ORDERS_REJECT";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";

export const GET_ALL_RESERVES_FROM_USER_PENDING = "GET_ALL_RESERVES_FROM_USER_PENDING";
export const GET_ALL_RESERVES_FROM_USER_REJECTED = "GET_ALL_RESERVES_FROM_USER_REJECTED";
export const GET_ALL_RESERVES_FROM_USER_SUCCESS = "GET_ALL_RESERVES_FROM_USER_SUCCESS";