export const GET_WALKER_REVIEW_PENDING = "GET_WALKER_REVIEW_PENDING";
export const GET_WALKER_REVIEW_SUCCESS = "GET_WALKER_REVIEW_SUCCESS";
export const GET_WALKER_REVIEW_REJECT = "GET_WALKER_REVIEW_REJECT";

export const CREATE_WALKER_REVIEW_PENDING = "CREATE_WALKER_REVIEW_PENDING";
export const CREATE_WALKER_REVIEW_SUCCESS = "CREATE_WALKER_REVIEW_SUCCESS";
export const CREATE_WALKER_REVIEW_REJECT = "CREATE_WALKER_REVIEW_REJECT";

export const EDIT_WALKER_REVIEW_PENDING = "EDIT_WALKER_REVIEW_PENDING";
export const EDIT_WALKER_REVIEW_SUCCESS = "EDIT_WALKER_REVIEW_SUCCESS";
export const EDIT_WALKER_REVIEW_REJECT = "EDIT_WALKER_REVIEW_REJECT";

export const DELETE_WALKER_REVIEW_PENDING = "DELETE_WALKER_REVIEW_PENDING";
export const DELETE_WALKER_REVIEW_SUCCESS = "DELETE_WALKER_REVIEW_SUCCESS";
export const DELETE_WALKER_REVIEW_REJECT = "DELETE_WALKER_REVIEW_REJECT";

