export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_REJECT = "CREATE_USER_REJECT";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const SELECT_OPTION_REGISTER = "SELECT_OPTION_REGISTER";

export const EDIT_USER_PENDING = "EDIT_USER_PENDING";
export const EDIT_USER_REJECT = "EDIT_USER_REJECT";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const GET_USER_BY_ID_PENDING = "GET_USER_BY_ID_PENDING";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_REJECT = "GET_USER_BY_ID_REJECT";

export const GET_ALL_USERS_PENDING = "GET_ALL_USERS_PENDING";
export const GET_ALL_USERS_REJECTED = "GET_ALL_USERS_REJECTED";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_REJECT = "LOGIN_USER_REJECT";

export const LOGOUT_USER = "LOGOUT_USER";
export const SAVE_TOKEN_IN_LOCAL_STORAGE = "SAVE_TOKEN_IN_LOCAL_STORAGE";

export const LOGIN_WITH_GOOGLE_PENDING = "LOGIN_WITH_GOOGLE_PENDING";
export const LOGIN_WITH_GOOGLE_SUCCESS = "LOGIN_WITH_GOOGLE_SUCCESS";
export const LOGIN_WITH_GOOGLE_REJECT = "LOGIN_WITH_GOOGLE_REJECT";

export const PASSWORD_EDIT_PENDING = "PASSWORD_EDIT_PENDING";
export const PASSWORD_EDIT_SUCCESS = "PASSWORD_EDIT_SUCCESS";
export const PASSWORD_EDIT_REJECT = "PASSWORD_EDIT_REJECT";

export const ROL_EDIT_PENDING = "ROL_EDIT_PENDING";
export const ROL_EDIT_SUCCESS = "ROL_EDIT_SUCCESS";
export const ROL_EDIT_REJECT = "ROL_EDIT_REJECT";

export const SEARCH_USER_BY_NAME_PENDING = "SEARCH_USER_BY_NAME_PENDING";
export const SEARCH_USER_BY_NAME_SUCCESS = "SEARCH_USER_BY_NAME_SUCCESS";
export const SEARCH_USER_BY_NAME_REJECT = "SEARCH_USER_BY_NAME_REJECT";

export const STATUS_EDIT_PENDING = "STATUS_EDIT_PENDING";
export const STATUS_EDIT_SUCCESS = "STATUS_EDIT_SUCCESS";
export const STATUS_EDIT_REJECT = "STATUS_EDIT_REJECT";

export const FORCE_PASSWORD_PENDING = "FORCE_PASSWORD_PENDING";
export const FORCE_PASSWORD_SUCCESS = "FORCE_PASSWORD_SUCCESS";
export const FORCE_PASSWORD_REJECT = "FORCE_PASSWORD_REJECT";

export const userTypes = {
  FORGOT_PASSWORD_PENDING: "FORGOT_PASSWORD_PENDING",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_REJECT: "FORGOT_PASSWORD_REJECT",

  RESET_PASSWORD_PENDING: "RESET_PASSWORD_PENDING",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_REJECT: "RESET_PASSWORD_REJECT",

  UPDATE_USER_STATUS_PENDING: "UPDATE_USER_STATUS_PENDING",
  UPDATE_USER_STATUS_SUCCESS: "UPDATE_USER_STATUS_SUCCESS",
  UPDATE_USER_STATUS_REJECT: "UPDATE_USER_STATUS_REJECT",
};
