export const GET_WALK_TO_WALKER = "GET_WALK_TO_WALKER";
export const POST_NEW_WALK = "POST_NEW_WALK";

export const GET_WALK_BY_ID_PENDING = "GET_WALK_BY_ID_PENDING";
export const GET_WALK_BY_ID_SUCCESS = "GET_WALK_BY_ID_SUCCESS";
export const GET_WALK_BY_ID_REJECT = "GET_WALK_BY_ID_REJECT";

export const GET_WALKS_PENDING = "GET_WALKS_PENDING";
export const GET_WALKS_SUCCESS = "GET_WALKS_SUCCESS";
export const GET_WALKS_REJECT = "GET_WALKS_REJECT";

export const EDIT_WALKS_PENDING = "EDIT_WALKS_PENDING";
export const EDIT_WALKS_REJECT = "EDIT_WALKS_REJECT";
export const EDIT_WALKS_SUCCESS = "EDIT_WALKS_SUCCESS";

export const DELETE_WALKS_BY_ID_PENDING = "DELETE_WALKS_BY_ID_PENDING";
export const DELETE_WALKS_BY_ID_REJECT = "DELETE_WALKS_BY_ID_REJECT";
export const DELETE_WALKS_BY_ID_SUCCESS = "DELETE_WALKS_BY_ID_SUCCESS";

export const GET_MYWALKS_PENDING = "GET_MYWALKS_PENDING";
export const GET_MYWALKS_SUCCESS = "GET_MYWALKS_SUCCESS";
export const GET_MYWALKS_REJECT = "GET_MYWALKS_REJECT";

export const walkTypes = {
  CREATE_NEW_WALK_PENDING: "CREATE_NEW_WALK_PENDING",
  CREATE_NEW_WALK_SUCCESS: "CREATE_NEW_WALK_SUCCESS",
  CREATE_NEW_WALK_REJECT: "CREATE_NEW_WALK_REJECT",
};

export const INACTIVE_WALK_BY_ID_PENDING = "INACTIVE_WALK_BY_ID_PENDING";
export const INACTIVE_WALK_BY_ID_SUCCESS = "INACTIVE_WALK_BY_ID_SUCCESS";
export const INACTIVE_WALK_BY_ID_REJECT = "INACTIVE_WALK_BY_ID_REJECT";
